# Generated by Django 3.2.7 on 2021-09-23 10:29

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='id')),
                ('title', models.CharField(help_text='Que faut-il faire ?', max_length=100, verbose_name='tâche')),
                ('task', models.CharField(choices=[('D', 'par défaut'), ('S', 'sport'), ('L', 'lecture'), ('P', 'personnel'), ('E', "liste d'envies"), ('T', 'travail'), ('F', 'formation')], default='D', help_text='type de tâche à faire', max_length=1, verbose_name='liste de tâche')),
                ('description', models.TextField(help_text='ajouter une description à la tâche', max_length=180, verbose_name='décrire votre tâche')),
                ('time_start', models.TimeField(help_text='heure de début', verbose_name='heure de début')),
                ('time_end', models.TimeField(help_text='heure de fin', verbose_name='heure de fin')),
                ('date_start', models.DateField(help_text='date de début', verbose_name='date de début')),
                ('date_end', models.DateField(help_text='date limite', verbose_name='date limite')),
                ('completed', models.BooleanField(default=False, verbose_name='tâche terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name_plural': 'todo',
                'db_table': 'db_todo',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['id', 'uuid'], name='id_index_todo'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(django.db.models.functions.text.Lower('title'), django.db.models.expressions.OrderBy(django.db.models.functions.text.Upper('task'), descending=True), name='title_task_name_idx'),
        ),
    ]
